download-speed: 5 # Kecepatan unduh dalam Mbps
download-folder: plugins # Pilihan: main, plugins, custom
custom-download-path: downloads # Digunakan jika download-folder adalah 'custom'
max-concurrent-downloads: 3 # Jumlah unduhan bersamaan maksimum
