# Konfigurasi untuk plugin Filed

# Kecepatan download maksimum dalam Mbps
download-speed: 5

# Folder tempat file unduhan disimpan
download-folder: plugins

# Jumlah maksimum unduhan simultan yang diizinkan
max-concurrent-downloads: 3
