# Konfigurasi untuk plugin Filed

# Kecepatan download maksimum dalam Mbps
download-speed: 5

# Folder tempat file unduhan disimpan
download-folder: downloads

# Maksimal ukuran file yang dapat diunduh (dalam MB)
max-file-size: 2048  # Default 2 GB

# Jumlah maksimum unduhan simultan yang diizinkan
max-concurrent-downloads: 3
