name: Filed
version: 1.0
main: com.example.filed.FiledPlugin  # Pastikan ini sesuai dengan nama kelas utama Anda
api-version: 1.21
commands:
  filed:
    description: Menyediakan perintah download dan reload
    usage: /filed <download|reload>