name: Filed
version: 1.0.0
main: com.example.filed.FiledPlugin
api-version: 1.19
commands:
  filed:
    description: Perintah utama untuk plugin Filed.
    usage: /filed <subcommand>
    permission: filed.use
    permission-message: Anda tidak memiliki izin untuk menggunakan perintah ini.
