name: Filed
main: com.example.filed.FiledPlugin
version: 1.3
description: Plugin untuk mengunduh file dari internet ke server Minecraft

commands:
  filed:
    description: Mengelola unduhan file
    usage: /filed <command>
    aliases:
      - filed
