name: Java CI with Gradle

on:
  push:
    branches: [ "tri.txt" ]
  pull_request:
    branches: [ "tri.txt" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: filed-plugin
        path: build/libs/*.jar
